### ISSUE TITLE
Xcode target for iOS

### ISSUE THREAD

**Issue by dmsurti** [3drepo/occt#1]
I use `cmake` to generate the project files for Xcode. After `cmake configure` step, I could not find any setting for building this library on iOS. (For example: VTK has `VTK_IOS_BUILD` setting). As such, the `Xcode` project has only OS X (64/32 bit builds).

* Any pointer/suggestions to build this library for iOS? 

I am open to submitting this as a PR if this needs to be added. I would just need to know the initial few steps in brief.

**Comment by carmenfan** [comment]
Hi,

We don't support iOS so I have never tried compiling for it. but a quick google is suggesting that you need to download the ios toolchain for cmake in order to generate the correct settings for it. 

See the top answer on [this page](http://stackoverflow.com/questions/12630970/compiling-for-ios-with-cmake)

**Comment by dmsurti** [comment]
@carmenfan Thanks for pointing out to the iOS-toolchain. That is really useful.
